/*
 * Frozen Fightbox C ABI v1 header.
 *
 * This file is test source truth. It deliberately is not regenerated by
 * cbindgen. Additive API versions belong in the canonical public header; the
 * declarations below must continue to compile and link unchanged.
 */

#ifndef FIGHTBOX_V1_H
#define FIGHTBOX_V1_H
#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum FbResult {
  FbOk = 0,
  FbInvalidArgument = 1,
  FbInvalidState = 2,
  FbIoError = 3,
  FbInvalidPackage = 4,
  FbInvalidBake = 5,
  FbBackendUnavailable = 6,
  FbBackendError = 7,
  FbBufferTooSmall = 8,
  FbPanic = 9,
} FbResult;

typedef enum FbQualityTier {
  FbQualityDesktop = 0,
  FbQualityMobile = 1,
} FbQualityTier;

typedef struct FbSession FbSession;

typedef struct FbVec3 {
  float east_m;
  float north_m;
  float up_m;
} FbVec3;

typedef struct FbPose {
  struct FbVec3 position;
  struct FbVec3 forward;
  struct FbVec3 up;
} FbPose;

typedef struct FbSessionConfig {
  uint32_t sample_rate_hz;
  uint32_t block_size_frames;
  uint32_t source_count;
  float default_source_level_db;
  uint32_t quality_tier;
} FbSessionConfig;

typedef struct FbSourceUpdate {
  uint8_t active;
  struct FbPose pose;
  struct FbVec3 linear_velocity_mps;
} FbSourceUpdate;

enum FbResult fb_session_create(const struct FbSessionConfig *config,
                                const char *package_path_utf8,
                                const char *bake_path_utf8,
                                struct FbSession **out_session);

enum FbResult fb_session_update_listener(struct FbSession *session,
                                         const struct FbPose *pose,
                                         const struct FbVec3 *linear_velocity_mps);

enum FbResult fb_session_update_source(struct FbSession *session,
                                       uint32_t source_index,
                                       const struct FbSourceUpdate *update);

enum FbResult fb_session_render_block(struct FbSession *session,
                                      const float *source_mono,
                                      size_t source_sample_count,
                                      float *out_interleaved_stereo,
                                      size_t out_sample_count);

enum FbResult fb_session_telemetry_json(struct FbSession *session,
                                        char *buffer,
                                        size_t buffer_capacity,
                                        size_t *out_required);

enum FbResult fb_session_destroy(struct FbSession *session);

#ifdef __cplusplus
}
#endif

#endif /* FIGHTBOX_V1_H */
