/* Regenerate from the repository root with cbindgen 0.29.2:
 * cbindgen --config crates/fightbox-ffi/cbindgen.toml \
 *   --crate fightbox-ffi --output crates/fightbox-ffi/include/fightbox.h
 */

#ifndef FIGHTBOX_H
#define FIGHTBOX_H

#pragma once

/* Generated by cbindgen from fightbox-ffi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
/* Frozen V1 source type: preserve the originally published C typedef even
 * though Rust carries an explicit u32 representation internally. */
typedef enum FbQualityTier {
  FbQualityDesktop = 0,
  FbQualityMobile = 1,
} FbQualityTier;

#define FB_ABI_VERSION_V2 2

#define FB_MAX_PROGRAM_CHANNELS_V2 2

#define FB_MAX_PRESENTATION_FEEDS_PER_SOURCE_V2 3

#define FB_MAX_PRESENTATION_FEEDS_V2 48

#define FB_MAX_ENVIRONMENTAL_ORDER_V2 2

#define FB_MAX_ENVIRONMENTAL_CHANNELS_V2 9

/**
 * Wave 0's public `MultiPoint` descriptor has a policy-fixed 1 m radius.
 *
 * `FbSourceProgramConfigV2.extent_m` still carries that scalar so a later
 * per-source-radius implementation does not require another C layout change.
 */
#define FB_MULTIPOINT_FIXED_EXTENT_METERS_V2 1.0

/**
 * Current `ExtentDescriptor::MultiPoint` stores point-cloud multiplicity in a
 * `u8`. This is distinct from Steam Audio's separate occlusion sample policy.
 */
#define FB_MAX_MULTIPOINT_COUNT_V2 255

#define FB_CELL_STREAM_PHASE_IDLE_V2 0

#define FB_CELL_STREAM_PHASE_PUBLISHING_V2 1

#define FB_CELL_STREAM_PHASE_PREPARED_V2 2

#define FB_CELL_STREAM_PHASE_CROSSFADING_V2 3

#define FB_CELL_STREAM_PHASE_TAIL_RETIRING_V2 4

#define FB_CELL_STREAM_PHASE_TAIL_COMPLETE_V2 5

#define FB_MAX_MACRO_ACTIVATIONS_V2 4

#define FB_MACRO_ELIGIBILITY_DETAILED_DIRECT_V2 (1 << 0)

#define FB_MACRO_ELIGIBILITY_STATISTICAL_GROUND_V2 (1 << 1)

#define FB_MACRO_ELIGIBILITY_BAKED_REFLECTIONS_V2 (1 << 2)

#define FB_MACRO_ELIGIBILITY_AUTHORED_ECHO_V2 (1 << 3)

#define FB_MACRO_ELIGIBILITY_SHARED_DIFFUSE_V2 (1 << 4)

/**
 * Fixed direct-bank component offsets within each logical source's 3 planes.
 */
#define FB_PRESENTATION_PLANE_DIRECT_CENTER_OFFSET_V2 0

#define FB_PRESENTATION_PLANE_WIDTH_POSITIVE_OFFSET_V2 1

#define FB_PRESENTATION_PLANE_WIDTH_NEGATIVE_OFFSET_V2 2

#define FB_PRESENTATION_COMPONENT_DIRECT_CENTER_V2 (1 << 0)

#define FB_PRESENTATION_COMPONENT_WIDTH_POSITIVE_V2 (1 << 1)

#define FB_PRESENTATION_COMPONENT_WIDTH_NEGATIVE_V2 (1 << 2)

/**
 * Reserved in Wave 0. Current HRTF-decoded echo taps cannot enter this route.
 */
#define FB_PRESENTATION_COMPONENT_DISCRETE_ECHO_V2 (1 << 3)

#define FB_SPATIAL_BLOCK_VALID_V2 (1 << 0)

#define FB_SPATIAL_BLOCK_DISCONTINUITY_V2 (1 << 1)

#define FB_SPATIAL_SOURCE_SAFETY_APPLIED_V2 (1 << 2)

#define FB_SPATIAL_OUTPUT_LIMITER_UNAPPLIED_V2 (1 << 3)

#define FB_SPATIAL_WORLD_UNROTATED_V2 (1 << 4)

#define FB_SPATIAL_FINAL_HRTF_UNAPPLIED_V2 (1 << 5)

#define FB_SPATIAL_SOURCE_DRIVE_APPLIED_V2 (1 << 6)

#define FB_SPATIAL_MONITOR_GAIN_UNAPPLIED_V2 (1 << 7)

#define FB_ABI_VERSION_V3 3

#define FB_MAX_MACRO_TOKEN_EVENTS_V3 4

#define FB_MAX_MACRO_PROGRAM_REQUESTS_V3 4

/**
 * Stable status returned by every fallible FFI operation.
 */
typedef enum FbResult {
  FbOk = 0,
  FbInvalidArgument = 1,
  FbInvalidState = 2,
  FbIoError = 3,
  FbInvalidPackage = 4,
  FbInvalidBake = 5,
  FbBackendUnavailable = 6,
  FbBackendError = 7,
  FbBufferTooSmall = 8,
  FbPanic = 9,
} FbResult;

/**
 * Construction-time route. A session never changes route after creation.
 */
enum FbRenderRouteV2
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbRenderLegacyFinalStereoV2 = 0,
  FbRenderNeutralSpatialV2 = 1,
};
#ifndef __cplusplus
typedef uint32_t FbRenderRouteV2;
#endif // __cplusplus

/**
 * Source geometry admitted by the Wave 0 transport seam.
 */
enum FbSourceGeometryV2
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbSourceGeometryPointV2 = 0,
  /**
   * One physical source and one derived Point presentation feed. The extent
   * only controls volumetric occlusion sampling; it does not create feeds.
   */
  FbSourceGeometryMultiPointV2 = 1,
  FbSourceGeometryLineSegmentV2 = 2,
  /**
   * Wave 0 structurally preserves two planes as L -> `WidthNegative` and
   * R -> `WidthPositive`, with `DirectCenter` inactive. Perceptual width,
   * PCA/M-S/crossfeed, distance-width law, and promotion remain Wave 2.
   */
  FbSourceGeometryStereoImageV2 = 3,
};
#ifndef __cplusplus
typedef uint32_t FbSourceGeometryV2;
#endif // __cplusplus

enum FbEnvironmentalChannelOrderV2
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbEnvironmentalAcnV2 = 0,
};
#ifndef __cplusplus
typedef uint32_t FbEnvironmentalChannelOrderV2;
#endif // __cplusplus

enum FbEnvironmentalNormalizationV2
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbEnvironmentalN3dV2 = 0,
};
#ifndef __cplusplus
typedef uint32_t FbEnvironmentalNormalizationV2;
#endif // __cplusplus

/**
 * Steam Audio world axes: +X right/east, +Y up, +Z back/south.
 *
 * The engine's ENU-to-Steam rotation is `(x, y, z) = (east, up, -north)`.
 * ACN channel numbers do not imply this axis convention, so it is carried
 * explicitly on every block.
 */
enum FbEnvironmentalBasisV2
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  /**
   * Engine domain axes: +X east, +Y north, +Z up.
   */
  FbEnvironmentalRightHandedEnuV2 = 0,
  /**
   * Steam Audio axes after the engine's one domain rotation.
   */
  FbEnvironmentalSteamXRightYUpZBackV2 = 1,
};
#ifndef __cplusplus
typedef uint32_t FbEnvironmentalBasisV2;
#endif // __cplusplus

enum FbSpatialOutputValidityV2
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbSpatialInvalidV2 = 0,
  FbSpatialValidV2 = 1,
  FbSpatialSilentDiscontinuityV2 = 2,
};
#ifndef __cplusplus
typedef uint32_t FbSpatialOutputValidityV2;
#endif // __cplusplus

enum FbPresentationPlacementV2
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbPresentationPoseV2 = 0,
  FbPresentationDirectionV2 = 1,
};
#ifndef __cplusplus
typedef uint32_t FbPresentationPlacementV2;
#endif // __cplusplus

/**
 * One of the four retained transient render reservations.
 */
enum FbMacroEventRoleV2
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbMacroCinematicImpulseV2 = 0,
  FbMacroStandardImpulseV2 = 1,
  FbMacroBallisticCrackV2 = 2,
  FbMacroBallisticBlastV2 = 3,
};
#ifndef __cplusplus
typedef uint32_t FbMacroEventRoleV2;
#endif // __cplusplus

/**
 * Whether dormant source media can be recovered at an exact program frame.
 */
enum FbMacroAssetTransportV2
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbMacroAssetSeekableV2 = 0,
  FbMacroAssetPreGeneratedV2 = 1,
  FbMacroAssetDeterministicGeneratorV2 = 2,
  FbMacroAssetNonSeekableLiveV2 = 3,
};
#ifndef __cplusplus
typedef uint32_t FbMacroAssetTransportV2;
#endif // __cplusplus

/**
 * Which renderer owns an activated event's final local leg.
 */
enum FbMacroRenderAuthorityV2
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbMacroRenderAuthorityNoneV2 = 0,
  FbMacroRenderAuthorityDetailedLocalV2 = 1,
  FbMacroRenderAuthorityFallbackV2 = 2,
};
#ifndef __cplusplus
typedef uint32_t FbMacroRenderAuthorityV2;
#endif // __cplusplus

/**
 * Stable reason for audible macro/shared-diffuse fallback.
 */
enum FbMacroFallbackReasonV2
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbMacroFallbackNoneV2 = 0,
  FbMacroFallbackMissingActiveCellV2 = 1,
  FbMacroFallbackStaleActiveCellV2 = 2,
  FbMacroFallbackMissingPackageAuthorityV2 = 3,
  FbMacroFallbackStalePackageAuthorityV2 = 4,
  FbMacroFallbackMissingProbeBakeAuthorityV2 = 5,
  FbMacroFallbackStaleProbeBakeAuthorityV2 = 6,
  FbMacroFallbackMissingEchoAuthorityV2 = 7,
  FbMacroFallbackStaleEchoAuthorityV2 = 8,
  FbMacroFallbackInvalidLocalLegV2 = 9,
};
#ifndef __cplusplus
typedef uint32_t FbMacroFallbackReasonV2;
#endif // __cplusplus

enum FbMacroTokenStatusV3
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbMacroTokenNoneV3 = 0,
  FbMacroTokenReservedV3 = 1,
  FbMacroTokenReadyV3 = 2,
  FbMacroTokenCommittedV3 = 3,
  FbMacroTokenAudioActiveV3 = 4,
  FbMacroTokenAudioAckedV3 = 5,
  FbMacroTokenTerminalRejectedV3 = 6,
};
#ifndef __cplusplus
typedef uint32_t FbMacroTokenStatusV3;
#endif // __cplusplus

enum FbMacroProgramModeV3
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbMacroProgramDetailedLocalV3 = 0,
  FbMacroProgramFallbackPointV3 = 1,
};
#ifndef __cplusplus
typedef uint32_t FbMacroProgramModeV3;
#endif // __cplusplus

enum FbMacroRenderDispositionV3
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbMacroRenderDiscardV3 = 0,
  FbMacroRenderCommitV3 = 1,
};
#ifndef __cplusplus
typedef uint32_t FbMacroRenderDispositionV3;
#endif // __cplusplus

enum FbMacroAudioAckStatusV3
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  FbMacroAudioCompletedV3 = 0,
  FbMacroAudioTerminalRejectedV3 = 1,
};
#ifndef __cplusplus
typedef uint32_t FbMacroAudioAckStatusV3;
#endif // __cplusplus

/**
 * Opaque control-thread-owned neutral cell prepared for one live session.
 */
typedef struct FbPreparedCell FbPreparedCell;

/**
 * Opaque retained session. Its layout is intentionally unavailable to C.
 */
typedef struct FbSession FbSession;

/**
 * Immutable session construction settings.
 */
typedef struct FbSessionConfig {
  uint32_t sample_rate_hz;
  uint32_t block_size_frames;
  uint32_t source_count;
  /**
   * Relative source level used by the quality governor.
   */
  float default_source_level_db;
  /**
   * One of `FbQualityTier`. Zero selects Desktop, preserving legacy
   * zero-initialized caller behavior. Unknown values are rejected.
   */
  uint32_t quality_tier;
} FbSessionConfig;

/**
 * Immutable V2 session construction settings.
 */
typedef struct FbSessionConfigV2 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint32_t sample_rate_hz;
  uint32_t block_size_frames;
  uint32_t source_count;
  float default_source_level_db;
  /**
   * One of `FbQualityTier`.
   */
  uint32_t quality_tier;
  /**
   * One of `FbRenderRouteV2`.
   */
  uint32_t render_route;
  /**
   * Requested environmental order in the inclusive range 0...2.
   */
  uint32_t environmental_order;
  /**
   * Must be zero. A later ABI version, not a silent reinterpretation, owns it.
   */
  uint32_t reserved[7];
} FbSessionConfigV2;

typedef struct FbMacroProductionBridgeConfigV3 {
  uint32_t abi_version;
  uint32_t struct_size;
  float diffuse_wet_gain;
  float diffuse_rt60_s;
  float diffuse_high_frequency_damping;
  float reserved_f32;
  uint64_t reserved[4];
} FbMacroProductionBridgeConfigV3;

/**
 * Construction-time program and presentation shape for one logical source.
 *
 * Wave 0 two-plane `StereoImage` preserves plane zero/left at the symmetric
 * `WidthNegative` endpoint and plane one/right at `WidthPositive`; its fixed
 * `DirectCenter` plane is inactive. Both planes share one physical trajectory.
 * A mono `StereoImage` inferably freezes `MonoExpanded` provenance; a two-plane
 * image inferably freezes `AuthoredStereo` provenance. Mono expansion remains
 * backend-unavailable in Wave 0, but the transport shape is reserved here.
 */
typedef struct FbSourceProgramConfigV2 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint32_t source_index;
  /**
   * One or two planar channels. Both share one physical propagation clock.
   */
  uint32_t channel_count;
  /**
   * One of `FbSourceGeometryV2`.
   */
  uint32_t source_geometry;
  /**
   * Declared point-cloud multiplicity. Nonzero only for `MultiPoint` and
   * currently constrained to 1...255. This does not configure Steam's
   * separate volumetric-occlusion sample count.
   */
  uint32_t multipoint_count;
  /**
   * Geometry extent in metres: zero for Point, the policy-fixed 1 m radius
   * for MultiPoint, or the positive full length/width for Line/StereoImage.
   */
  float extent_m;
  float reserved_f32;
  uint64_t reserved[4];
} FbSourceProgramConfigV2;

/**
 * Immutable identity and host-accounted size estimates for one prepared cell.
 * The 128-bit keys are opaque stable package identifiers split high/low for C.
 */
typedef struct FbCellConfigV2 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint64_t city_key_high;
  uint64_t city_key_low;
  uint64_t cell_key_high;
  uint64_t cell_key_low;
  uint64_t raw_cell_bytes;
  uint64_t prepared_resident_bytes;
  uint64_t reserved[4];
} FbCellConfigV2;

/**
 * Atomic control-side view of the neutral render swap lifecycle.
 */
typedef struct FbCellStreamStateV2 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint32_t phase;
  uint32_t reserved_u32;
  /**
   * Generation currently owned by the simulation/control half. During
   * `Prepared` this is still the old world; after offer it is the candidate.
   */
  uint64_t control_generation;
  uint64_t reserved[4];
} FbCellStreamStateV2;

/**
 * Host weather frozen for macro and local spectral planning.
 */
typedef struct FbAtmosphereObservationV2 {
  uint32_t abi_version;
  uint32_t struct_size;
  float temperature_c;
  float relative_humidity_percent;
  float pressure_kpa;
  float reserved_f32;
  uint64_t reserved[4];
} FbAtmosphereObservationV2;

/**
 * Three-component vector in right-handed local ENU coordinates.
 */
typedef struct FbVec3 {
  float east_m;
  float north_m;
  float up_m;
} FbVec3;

/**
 * One member of an atomically admitted macro-event group.
 */
typedef struct FbMacroEventRequestV2 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint64_t event_id;
  uint64_t atomic_group_id;
  uint32_t role;
  uint32_t asset_transport;
  uint64_t asset_key;
  uint64_t emission_frame;
  uint64_t program_seek_frame;
  uint64_t retained_frames_after_activation;
  struct FbVec3 emitter_position_enu;
  float local_horizon_m;
  /**
   * Zero means the asset is dry; one means the recording carries motion.
   */
  uint32_t recording_carries_motion;
  uint32_t reserved_u32;
  uint64_t reserved[4];
} FbMacroEventRequestV2;

typedef struct FbMacroEchoAnchorBindingV3 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint64_t event_id;
  uint8_t anchor_key[16];
  uint64_t reserved[4];
} FbMacroEchoAnchorBindingV3;

typedef struct FbMacroPrepareEventV3 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint64_t event_id;
  uint64_t atomic_group_id;
  uint32_t role;
  uint32_t reserved_u32;
  uint64_t asset_key;
  uint64_t activation_frame;
  uint64_t program_seek_frame;
  uint64_t tail_deadline_frame;
  uint64_t reserved[2];
} FbMacroPrepareEventV3;

typedef struct FbMacroPrepareBatchV3 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint64_t token_id;
  uint64_t lookahead_frame;
  uint32_t event_count;
  uint32_t status;
  struct FbMacroPrepareEventV3 events[FB_MAX_MACRO_TOKEN_EVENTS_V3];
  uint64_t reserved[2];
} FbMacroPrepareBatchV3;

typedef struct FbMacroReadyAssetV3 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint64_t token_id;
  uint64_t event_id;
  uint32_t role;
  uint32_t source_index;
  uint64_t asset_key;
  uint64_t program_seek_frame;
  uint64_t discontinuity_sequence;
  uint64_t reserved[2];
} FbMacroReadyAssetV3;

/**
 * Position and orientation in right-handed local ENU coordinates.
 */
typedef struct FbPose {
  struct FbVec3 position;
  struct FbVec3 forward;
  struct FbVec3 up;
} FbPose;

/**
 * Complete control-thread update for one stable source index.
 */
typedef struct FbSourceUpdate {
  /**
   * Zero means inactive; any other value means active.
   */
  uint8_t active;
  struct FbPose pose;
  struct FbVec3 linear_velocity_mps;
} FbSourceUpdate;

/**
 * One complete control-thread frame for a session's stable source set.
 *
 * Source record ordinal is the stable zero-based source index. The caller
 * supplies exactly the session's configured source count; an extended stride
 * may append caller-private bytes to each current `FbSourceUpdate` prefix.
 * `source_updates` names one contiguous readable allocation spanning exactly
 * `(source_count - 1) * source_update_stride_bytes + sizeof(FbSourceUpdate)`
 * bytes (or more) for the duration of the call.
 */
typedef struct FbControlFrameV2 {
  uint32_t abi_version;
  uint32_t struct_size;
  const struct FbSourceUpdate *source_updates;
  uint32_t source_count;
  uint32_t source_update_stride_bytes;
  struct FbPose listener_pose;
  struct FbVec3 listener_linear_velocity_mps;
  /**
   * Must be zero. A later ABI version, not a silent reinterpretation, owns it.
   */
  uint64_t reserved[4];
} FbControlFrameV2;

typedef struct FbMacroCommitResultV3 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint64_t token_id;
  uint32_t status;
  uint32_t event_count;
  uint64_t direct_generation;
  uint64_t effective_frame;
  uint64_t tail_deadline_frame;
  uint64_t reserved[2];
} FbMacroCommitResultV3;

typedef struct FbMacroAudioAckV3 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint64_t token_id;
  uint64_t event_id;
  uint32_t role;
  uint32_t status;
  uint64_t asset_key;
  uint32_t source_index;
  uint32_t reserved_u32;
  uint64_t discontinuity_sequence;
  uint64_t direct_generation;
  uint64_t effective_frame;
  uint64_t program_seek_frame;
  uint64_t reserved[1];
} FbMacroAudioAckV3;

/**
 * One due event after macro transport and adopted-cell authority resolution.
 */
typedef struct FbMacroActivationV2 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint32_t active;
  uint32_t role;
  uint32_t render_authority;
  uint32_t fallback_reason;
  uint32_t eligibility_bits;
  uint32_t shared_diffuse_fallback;
  uint64_t event_id;
  uint64_t atomic_group_id;
  uint64_t asset_key;
  uint64_t emission_frame;
  uint64_t program_seek_frame;
  uint64_t macro_arrival_frame;
  uint64_t fallback_ear_arrival_frame;
  uint64_t tail_deadline_frame;
  uint64_t authority_world_generation;
  float macro_distance_gain;
  float macro_atmosphere_gain_db[8];
  struct FbVec3 ingress_proxy_enu;
  struct FbVec3 remote_direction_enu;
  float local_distance_m;
  uint64_t local_delay_frames;
  float local_distance_gain;
  float local_atmosphere_gain_db[8];
  uint64_t reserved[4];
} FbMacroActivationV2;

/**
 * Fixed-capacity result of one control-thread due-event activation pass.
 */
typedef struct FbMacroActivationBatchV2 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint32_t activation_count;
  uint32_t reserved_u32;
  struct FbMacroActivationV2 activations[FB_MAX_MACRO_ACTIVATIONS_V2];
  uint64_t reserved[4];
} FbMacroActivationBatchV2;

typedef struct FbMacroProgramRequestV3 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint64_t token_id;
  uint64_t event_id;
  uint64_t asset_key;
  uint32_t role;
  uint32_t mode;
  uint32_t source_index;
  uint32_t reserved_u32;
  uint64_t program_seek_frame;
  uint64_t discontinuity_sequence;
  uint64_t asset_frame_start;
  uint32_t frame_count;
  uint32_t destination_frame_offset;
  uint64_t block_start_frame;
  uint64_t reserved[2];
} FbMacroProgramRequestV3;

typedef struct FbMacroProgramRequestBatchV3 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint64_t token_id;
  uint64_t block_start_frame;
  uint32_t request_count;
  uint32_t status;
  struct FbMacroProgramRequestV3 requests[FB_MAX_MACRO_PROGRAM_REQUESTS_V3];
  uint64_t reserved[2];
} FbMacroProgramRequestBatchV3;

/**
 * One source-major planar input record.
 *
 * Channel zero begins at `samples`; channel one, when present, begins at
 * `samples + channel_stride_samples`. Each active plane contains exactly the
 * configured block length of finite `float` samples. For a two-plane
 * `StereoImage`, channel zero is left/`WidthNegative` and channel one is
 * right/`WidthPositive`.
 */
typedef struct FbSourceProgramInputV2 {
  uint32_t source_index;
  uint32_t channel_count;
  const float *samples;
  size_t sample_count;
  size_t channel_stride_samples;
  uint64_t reserved[4];
} FbSourceProgramInputV2;

/**
 * Caller-owned contiguous planar output bank.
 *
 * Plane `n` starts at `samples + n * plane_stride_samples`. In the direct bank,
 * logical source `s` owns planes `s * 3 + {center, width+, width-}` using the
 * three `FB_PRESENTATION_PLANE_*_OFFSET_V2` constants. `DiscreteEcho` reserves
 * a component bit but has no plane. V2 writes only the configured block length
 * and never touches padding or guard samples.
 */
typedef struct FbPlanarOutputV2 {
  float *samples;
  size_t sample_capacity;
  uint32_t plane_capacity;
  uint32_t reserved_u32;
  size_t plane_stride_samples;
  uint64_t reserved[4];
} FbPlanarOutputV2;

/**
 * Metadata parallel to one direct-presentation output plane.
 */
typedef struct FbPresentationFeedMetadataV2 {
  uint32_t valid;
  uint32_t source_index;
  /**
   * Exactly one `FB_PRESENTATION_COMPONENT_*_V2` bit.
   */
  uint32_t component;
  /**
   * One of `FbPresentationPlacementV2`.
   */
  uint32_t placement;
  /**
   * Correlated absolute ENU pose; diagnostic when placement is Direction.
   */
  struct FbPose pose;
  /**
   * Listener-to-feed unit ENU direction. Displacement with squared length
   * at most `1e-12 m^2`, including coincidence, is +north.
   */
  struct FbVec3 direction_enu;
  uint32_t processing_latency_frames;
  uint32_t reserved[3];
} FbPresentationFeedMetadataV2;

/**
 * Per-block truth accompanying the direct and environmental planar banks.
 */
typedef struct FbSpatialBlockMetadataV2 {
  uint32_t abi_version;
  uint32_t struct_size;
  uint32_t sample_rate_hz;
  uint32_t block_size_frames;
  uint64_t block_start_frame;
  uint64_t generation;
  uint64_t discontinuity_sequence;
  /**
   * One of `FbSpatialOutputValidityV2`.
   */
  uint32_t validity;
  /**
   * Count of valid entries across the fixed 48-plane presentation bank.
   */
  uint32_t active_presentation_feed_count;
  uint32_t environmental_order;
  uint32_t environmental_channel_count;
  uint32_t environmental_latency_frames;
  uint32_t component_mask;
  uint32_t flags;
  uint32_t environmental_channel_order;
  uint32_t environmental_normalization;
  uint32_t environmental_basis;
  uint32_t reserved_u32;
  uint64_t reserved[4];
} FbSpatialBlockMetadataV2;

/**
 * One allocation-free spatial render call.
 *
 * Record strides permit additive structure growth without changing this
 * function signature. V2 requires strides at least as large as the current
 * record and aligned for that record. All reserved fields must be zero.
 */
typedef struct FbSpatialRenderBlockV2 {
  uint32_t abi_version;
  uint32_t struct_size;
  const struct FbSourceProgramInputV2 *source_programs;
  uint32_t source_program_count;
  uint32_t source_program_stride_bytes;
  struct FbPlanarOutputV2 direct_output;
  struct FbPlanarOutputV2 environmental_output;
  struct FbPresentationFeedMetadataV2 *feed_metadata;
  uint32_t feed_metadata_capacity;
  uint32_t feed_metadata_stride_bytes;
  struct FbSpatialBlockMetadataV2 *block_metadata;
  uint64_t reserved[4];
} FbSpatialRenderBlockV2;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a retained session.
 *
 * Thread safety: call on the control thread before starting audio. `config`,
 * both UTF-8 NUL-terminated paths, and `out_session` are borrowed only for
 * this call. On failure, `*out_session` is null. The package path names a
 * `.fightbox` directory; the bake path names a directory containing
 * `probe-batch.bin`, `probe-batch-metadata.json`, and
 * `city-bake-manifest.json`.
 */
enum FbResult fb_session_create(const struct FbSessionConfig *config,
                                const char *package_path_utf8,
                                const char *bake_path_utf8,
                                struct FbSession **out_session);

/**
 * Creates an immutable-route V2 session.
 *
 * The universal `abi_version`/`struct_size` header is validated before the
 * current config prefix is copied. Both paths are still parsed for every
 * otherwise-valid route. Neutral creation validates and retains immutable
 * world/config inputs, then collects every source shape. The final source
 * configuration binds Steam simulation, RuntimeGraph, and the packed render
 * scratch together on the control thread before rendering becomes available.
 * Legacy route construction delegates to the preserved builder. On every
 * failure, `*out_session` is null.
 *
 * # Safety
 *
 * `config` must name at least its readable eight-byte V2 header and, when that
 * header advertises the current size, the complete readable current prefix.
 * Both paths must be readable NUL-terminated strings. `out_session` must be a
 * writable, aligned pointer for this call.
 */
enum FbResult fb_session_create_v2(const struct FbSessionConfigV2 *config,
                                   const char *package_path_utf8,
                                   const char *bake_path_utf8,
                                   struct FbSession **out_session);

/**
 * Explicitly opts a neutral session into the additive tokened macro bridge.
 *
 * Control thread only, immediately after `fb_session_create_v2` and before any
 * source configuration. V2 activation behavior remains unchanged for sessions
 * that never call this symbol.
 *
 * # Safety
 * `session` is a live neutral handle and `config` is one readable current V3
 * scalar configuration.
 */
enum FbResult fb_session_enable_macro_production_bridge_v3(struct FbSession *session,
                                                           const struct FbMacroProductionBridgeConfigV3 *config);

/**
 * Freezes one logical source's program and presentation shape.
 *
 * This is a construction-time control-thread call. A source may be configured
 * once, before the audio thread begins. Legacy-route sessions reject it.
 *
 * # Safety
 *
 * `session` must be a live handle. `config` follows the same universal-header
 * and current-prefix readability contract as [`fb_session_create_v2`].
 */
enum FbResult fb_session_configure_source_v2(struct FbSession *session,
                                             const struct FbSourceProgramConfigV2 *config);

/**
 * Prepares a neutral spatial V2 session for its first render.
 *
 * Thread safety: control thread only, after every source shape and the actual
 * initial listener/source states have been published. This mandatory barrier
 * performs no public render: a successful call leaves the first render at
 * frame and timing-observation zero. Legacy-route sessions reject it.
 *
 * # Safety
 *
 * `session` must be a live handle.
 */
enum FbResult fb_session_prepare_spatial_v2(struct FbSession *session);

/**
 * Builds and primes one neighboring neutral cell on the control thread.
 *
 * This call may perform file I/O, decompression, Steam scene construction,
 * simulation, and allocation. Hosts should dispatch it away from the audio
 * callback. The active session remains renderable throughout. The returned
 * handle is bound to `session` and must be offered or destroyed exactly once.
 *
 * # Safety
 *
 * `session` must be a live neutral handle. `config` follows the V2 readable
 * prefix contract, both paths are readable NUL-terminated UTF-8, and
 * `out_prepared_cell` is writable for this call.
 */
enum FbResult fb_session_prepare_cell_v2(struct FbSession *session,
                                         const char *package_path_utf8,
                                         const char *bake_path_utf8,
                                         const struct FbCellConfigV2 *config,
                                         struct FbPreparedCell **out_prepared_cell);

/**
 * Offers one prepared cell for block-boundary adoption.
 *
 * Success consumes `prepared_cell`. Failure leaves the handle and its world
 * intact, so the host may retry or destroy it. The render thread performs the
 * eight-block direct/path transition and tail-only retirement.
 *
 * # Safety
 *
 * Both handles must be live, and the prepared handle must have been created
 * for this exact session. Control thread only.
 */
enum FbResult fb_session_offer_prepared_cell_v2(struct FbSession *session,
                                                struct FbPreparedCell *prepared_cell);

/**
 * Returns the lock-free neutral cell adoption/retirement phase.
 *
 * # Safety
 *
 * `session` is live and `out_state` is writable for this call. Control thread
 * only; no SDK object is touched.
 */
enum FbResult fb_session_cell_stream_state_v2(struct FbSession *session,
                                              struct FbCellStreamStateV2 *out_state);

/**
 * Collects a TailComplete cell generation on the control thread. Idempotent.
 *
 * # Safety
 *
 * `session` must be a live neutral handle.
 */
enum FbResult fb_session_collect_retired_cell_v2(struct FbSession *session);

/**
 * Destroys an unoffered prepared-cell handle on the caller's control thread.
 *
 * # Safety
 *
 * `prepared_cell` must be a live handle returned by
 * [`fb_session_prepare_cell_v2`] and not previously consumed or destroyed.
 */
enum FbResult fb_prepared_cell_destroy_v2(struct FbPreparedCell *prepared_cell);

/**
 * Freezes the atmosphere used by macro transport for this session.
 *
 * A null observation explicitly selects the deterministic fallback. Invalid
 * host weather also freezes the complete fallback with its stable provenance.
 * The atmosphere may be selected only before the first macro group is
 * admitted or activated.
 *
 * # Safety
 *
 * `session` must be a live neutral handle. A non-null `observation` follows
 * the V2 readable-prefix contract. Control thread only.
 */
enum FbResult fb_session_freeze_atmosphere_v2(struct FbSession *session,
                                              const struct FbAtmosphereObservationV2 *observation);

/**
 * Plans and atomically admits one macro-event group into the session queue.
 *
 * The engine derives delay, distance, ingress proxy, bearing, and atmospheric
 * conditioning from the current listener truth. A group contains one to four
 * contiguous requests with one unique retained role each. No active render
 * voice or decoded PCM is allocated while the event remains dormant.
 *
 * # Safety
 *
 * `session` is a live neutral handle and `requests` names `request_count`
 * readable current V2 request structures. Control thread only.
 */
enum FbResult fb_session_admit_macro_event_group_v2(struct FbSession *session,
                                                    const struct FbMacroEventRequestV2 *requests,
                                                    uint32_t request_count);

/**
 * Binds one already-admitted dormant macro event to a real authored static
 * ingress anchor. The binding must precede token preparation; all-zero remains
 * structural echo Off and V2 admission never invents an anchor.
 *
 * # Safety
 * `session` is a live bridge-enabled neutral handle and `binding` is one
 * readable, aligned current V3 scalar record. Control thread only.
 */
enum FbResult fb_session_bind_macro_echo_anchor_v3(struct FbSession *session,
                                                   const struct FbMacroEchoAnchorBindingV3 *binding);

/**
 * Reserves the earliest common macro activation frame within a lookahead
 * horizon without consuming the dormant event or occupying a render role.
 * Swift uses the returned scalar records to prepare exact canonical seeks.
 *
 * # Safety
 * `session` is a live bridge-enabled neutral handle. `out_batch` is writable,
 * aligned, and initialized with a current V3 header. Control thread only.
 */
enum FbResult fb_session_prepare_macro_token_v3(struct FbSession *session,
                                                uint64_t lookahead_frame,
                                                struct FbMacroPrepareBatchV3 *out_batch);

/**
 * Copies an all-or-nothing set of even canonical-provider readiness tokens
 * into the held dormant reservation. No async/provider object crosses C.
 *
 * # Safety
 * `ready` names `ready_count` readable current V3 scalar records. Control
 * thread only.
 */
enum FbResult fb_session_stage_macro_ready_v3(struct FbSession *session,
                                              const struct FbMacroReadyAssetV3 *ready,
                                              uint32_t ready_count);

/**
 * Commits one ready token on its exact complete control frame. The direct
 * generation is the transaction boundary: a failed direct pass leaves the
 * reservation retryable, while a later optional-phase failure is already
 * committed and reported in `out_result`.
 *
 * # Safety
 * `frame` is one readable current V2 complete frame and `out_result` is a
 * writable initialized current V3 record. Control thread only.
 */
enum FbResult fb_session_update_control_frame_macro_v3(struct FbSession *session,
                                                       const struct FbControlFrameV2 *frame,
                                                       uint64_t token_id,
                                                       struct FbMacroCommitResultV3 *out_result);

/**
 * Discards a matching pre-commit token and returns its records to dormant
 * selection. Provider release remains Swift control-side.
 *
 * # Safety
 * `session` is a live bridge-enabled neutral handle. Control thread only.
 */
enum FbResult fb_session_discard_macro_token_v3(struct FbSession *session, uint64_t token_id);

/**
 * Polls one terminal fixed-copy audio acknowledgement. Polling never
 * releases Swift playback or control-owned ingress authority.
 *
 * # Safety
 * `out_ack` is writable, aligned, and initialized with a current V3 header.
 * Control thread only.
 */
enum FbResult fb_session_poll_macro_ack_v3(struct FbSession *session,
                                           struct FbMacroAudioAckV3 *out_ack);

/**
 * Finalizes a previously polled acknowledgement after Swift has released the
 * exact readiness token on its serialized control queue.
 *
 * # Safety
 * `ack` is one readable current V3 scalar acknowledgement. Control thread
 * only and only after provider release.
 */
enum FbResult fb_session_finalize_macro_ack_v3(struct FbSession *session,
                                               const struct FbMacroAudioAckV3 *ack);

/**
 * Consumes every currently due role-eligible macro event exactly once.
 *
 * The returned records carry disjoint macro conditioning and final-local-leg
 * values. The host applies the macro fields once, seeks the canonical asset to
 * `program_seek_frame`, and gives only the local leg to the detailed renderer.
 *
 * # Safety
 *
 * `session` must be a live neutral handle and `out_batch` must be writable,
 * aligned, and initialized with a current V2 header. Control thread only.
 */
enum FbResult fb_session_activate_macro_events_v2(struct FbSession *session,
                                                  uint64_t current_frame,
                                                  struct FbMacroActivationBatchV2 *out_batch);

/**
 * Releases one active retained event role at a measured energy floor.
 *
 * Deadline retirement remains automatic. An explicit release must identify
 * both the role and event so it cannot steal another member's reservation.
 *
 * # Safety
 *
 * `session` must be a live neutral handle. Control thread only.
 */
enum FbResult fb_session_release_macro_event_v2(struct FbSession *session,
                                                uint32_t role,
                                                uint64_t event_id);

/**
 * Begins one allocation-free macro provider transaction for the session's
 * current callback frame. The output may be empty; bound macro slots must
 * still remain silent unless a returned interval names them.
 *
 * # Safety
 * `out_batch` is writable, aligned, and initialized with a current V3 header.
 * Audio thread only, immediately before `fb_session_render_spatial_v2`.
 */
enum FbResult fb_session_macro_render_begin_v3(struct FbSession *session,
                                               struct FbMacroProgramRequestBatchV3 *out_batch);

/**
 * Completes or discards the previously begun provider interval transaction.
 * Discard clears only staged frame counts; it emits no acknowledgement and
 * leaves each active role retryable at the same engine callback frame.
 *
 * # Safety
 * `session` is a live bridge-enabled neutral handle. Audio thread only.
 */
enum FbResult fb_session_macro_render_end_v3(struct FbSession *session, uint32_t disposition);

/**
 * Renders one neutral spatial callback block.
 *
 * The complete argument graph is validated before an output byte or the
 * session block clock can change. Runtime and Steam render into session-owned
 * packed scratch; only a successful RuntimeGraph call is scattered into the
 * caller's potentially strided banks. Legacy-route sessions reject this entry
 * point.
 *
 * # Safety
 *
 * `session` must be live. `block` and every active record/buffer follow the
 * V2 header, capacity, alignment, readability, writability, and non-overlap
 * contracts declared by their public structures.
 */
enum FbResult fb_session_render_spatial_v2(struct FbSession *session,
                                           const struct FbSpatialRenderBlockV2 *block);

/**
 * Publishes a listener pose and advances the control-side simulation cadence.
 *
 * Thread safety: control thread only. Calls must not overlap other update or
 * telemetry calls. This may run Steam Audio simulation and must never be
 * called from the audio callback. It may run concurrently with render.
 */
enum FbResult fb_session_update_listener(struct FbSession *session,
                                         const struct FbPose *pose,
                                         const struct FbVec3 *linear_velocity_mps);

/**
 * Publishes one source's motion and advances the control-side simulation cadence.
 *
 * Thread safety: control thread only, serialized with listener updates and
 * telemetry. `source_index` is stable and zero-based.
 */
enum FbResult fb_session_update_source(struct FbSession *session,
                                       uint32_t source_index,
                                       const struct FbSourceUpdate *update);

/**
 * Publishes one complete listener/source control frame and advances simulation once.
 *
 * The frame carries exactly one source record for every stable source index.
 * Its current prefixes are copied and semantically validated in full before
 * either route's control truth, publications, or lifecycle state can change.
 * A valid frame uses the same synchronous direct/path/reflection scheduler as
 * the granular calls. Successful direct simulation consumes exactly one
 * cadence tick for the whole frame; direct failure consumes none, while a
 * later pathing or reflection failure retains the already-consumed tick. Both
 * legacy-final-stereo and neutral-spatial sessions accept it.
 * `FbInvalidArgument` is a total no-op. `FbBackendError` is not transactional:
 * neutral stages the accepted update and revokes pre-render preparation before
 * direct simulation, then publishes correlated propagation after direct
 * succeeds; legacy publishes its frozen orientation and activity snapshots
 * before direct simulation.
 * Neutral publication remains correlated by the direct-generation token.
 * Legacy deliberately preserves its frozen independent orientation, active,
 * and Steam propagation snapshots, including their bounded adjacent-snapshot
 * callback skew; this additive entry point does not reopen that fallback ABI.
 *
 * Thread safety: control thread only, serialized with granular updates,
 * preparation, and telemetry. This may run Steam Audio simulation and must
 * never be called from the audio callback.
 *
 * # Safety
 *
 * `session` must be a live handle. `frame` must name at least its readable
 * eight-byte V2 header and, when that header advertises the current size, the
 * complete current prefix. Its source pointer must name one contiguous
 * readable allocation spanning `(source_count - 1) * stride + 52` bytes for
 * the declared strided source records.
 */
enum FbResult fb_session_update_control_frame_v2(struct FbSession *session,
                                                 const struct FbControlFrameV2 *frame);

/**
 * Renders exactly one configured block.
 *
 * `source_mono` contains `source_count * block_size_frames` finite samples in
 * source-major order. `out_interleaved_stereo` contains
 * `block_size_frames * 2` writable samples and must not overlap the input.
 *
 * Thread safety: one audio thread only. The function is allocation-free and
 * lock-free after construction. It may run concurrently with control updates.
 */
enum FbResult fb_session_render_block(struct FbSession *session,
                                      const float *source_mono,
                                      size_t source_sample_count,
                                      float *out_interleaved_stereo,
                                      size_t out_sample_count);

/**
 * Copies a NUL-terminated delivered-quality/timing JSON snapshot.
 *
 * Thread safety: control thread only, serialized with updates. `out_required`
 * always receives the required byte count including the NUL terminator.
 * Passing a null buffer with zero capacity is the supported size query.
 */
enum FbResult fb_session_telemetry_json(struct FbSession *session,
                                        char *buffer,
                                        size_t buffer_capacity,
                                        size_t *out_required);

/**
 * Destroys a session and releases all Rust and Steam Audio resources.
 *
 * Thread safety: call only after the control and audio threads are stopped
 * and joined. A handle must be destroyed exactly once.
 */
enum FbResult fb_session_destroy(struct FbSession *session);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FIGHTBOX_H */
