/* Generated by cbindgen from fightbox-ffi. Do not edit by hand. */
/* Regenerate from the repository root:
 * cbindgen --config crates/fightbox-ffi/cbindgen.toml \
 *   --crate fightbox-ffi --output crates/fightbox-ffi/include/fightbox.h
 */

#ifndef FIGHTBOX_H
#define FIGHTBOX_H
#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum FbResult {
  FbOk = 0,
  FbInvalidArgument = 1,
  FbInvalidState = 2,
  FbIoError = 3,
  FbInvalidPackage = 4,
  FbInvalidBake = 5,
  FbBackendUnavailable = 6,
  FbBackendError = 7,
  FbBufferTooSmall = 8,
  FbPanic = 9,
} FbResult;

typedef enum FbQualityTier {
  FbQualityDesktop = 0,
  FbQualityMobile = 1,
} FbQualityTier;

typedef struct FbSession FbSession;

typedef struct FbVec3 {
  float east_m;
  float north_m;
  float up_m;
} FbVec3;

typedef struct FbPose {
  struct FbVec3 position;
  struct FbVec3 forward;
  struct FbVec3 up;
} FbPose;

typedef struct FbSessionConfig {
  uint32_t sample_rate_hz;
  uint32_t block_size_frames;
  uint32_t source_count;
  float default_source_level_db;
  /**
   * One of `FbQualityTier`. Zero selects Desktop, preserving legacy
   * zero-initialized caller behavior. Unknown values are rejected.
   */
  uint32_t quality_tier;
} FbSessionConfig;

typedef struct FbSourceUpdate {
  uint8_t active;
  struct FbPose pose;
  struct FbVec3 linear_velocity_mps;
} FbSourceUpdate;

/**
 * Creates a retained session.
 *
 * Thread safety: call on the control thread before starting audio. `config`,
 * both UTF-8 NUL-terminated paths, and `out_session` are borrowed only for
 * this call. On failure, `*out_session` is null. The package path names a
 * `.fightbox` directory; the bake path names a directory containing
 * `probe-batch.bin`, `probe-batch-metadata.json`, and
 * `city-bake-manifest.json`.
 */
enum FbResult fb_session_create(const struct FbSessionConfig *config,
                                const char *package_path_utf8,
                                const char *bake_path_utf8,
                                struct FbSession **out_session);

/**
 * Publishes a listener pose and advances the control-side simulation cadence.
 *
 * Thread safety: control thread only. Calls must not overlap other update or
 * telemetry calls. This may run Steam Audio simulation and must never be
 * called from the audio callback. It may run concurrently with render.
 */
enum FbResult fb_session_update_listener(struct FbSession *session,
                                         const struct FbPose *pose,
                                         const struct FbVec3 *linear_velocity_mps);

/**
 * Publishes one source's motion and advances the control-side simulation cadence.
 *
 * Thread safety: control thread only, serialized with listener updates and
 * telemetry. `source_index` is stable and zero-based.
 */
enum FbResult fb_session_update_source(struct FbSession *session,
                                       uint32_t source_index,
                                       const struct FbSourceUpdate *update);

/**
 * Renders exactly one configured block.
 *
 * `source_mono` contains `source_count * block_size_frames` finite samples in
 * source-major order. `out_interleaved_stereo` contains
 * `block_size_frames * 2` writable samples and must not overlap the input.
 *
 * Thread safety: one audio thread only. The function is allocation-free and
 * lock-free after construction. It may run concurrently with control updates.
 */
enum FbResult fb_session_render_block(struct FbSession *session,
                                      const float *source_mono,
                                      size_t source_sample_count,
                                      float *out_interleaved_stereo,
                                      size_t out_sample_count);

/**
 * Copies a NUL-terminated delivered-quality/timing JSON snapshot.
 *
 * Thread safety: control thread only, serialized with updates. `out_required`
 * always receives the required byte count including the NUL terminator.
 * Passing a null buffer with zero capacity is the supported size query.
 */
enum FbResult fb_session_telemetry_json(struct FbSession *session,
                                        char *buffer,
                                        size_t buffer_capacity,
                                        size_t *out_required);

/**
 * Destroys a session and releases all Rust and Steam Audio resources.
 *
 * Thread safety: call only after the control and audio threads are stopped
 * and joined. A handle must be destroyed exactly once.
 */
enum FbResult fb_session_destroy(struct FbSession *session);

#ifdef __cplusplus
}
#endif

#endif /* FIGHTBOX_H */
